"""create_determine_table

Revision ID: 2dc5bcddf7aa
Revises: 
Create Date: 2026-05-16 13:46:51.200455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2dc5bcddf7aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('determine',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('fonte_file', sa.Text(), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('source', sa.Enum('upload', 'gcs_bulk', name='source_enum'), nullable=False, server_default='upload'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('determine')
    # ### end Alembic commands ###
